change og

diff --git a/.github/workflows/action.yaml b/.github/workflows/action.yaml
--- a/.github/workflows/action.yaml
+++ b/.github/workflows/action.yaml
@@ -1,5 +1,4 @@
-name: Deploy to SPC with OIDC
-
+name: Deploy to SPC with OIDC (Shell Script)
 on:
   push:
     branches:
@@ -16,17 +15,43 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v3
 
-      - name: Make deploy script executable
-        run: chmod +x oidc.sh
+      - name: Configure SPC Credentials
+        id: spc_credentials
+        run: |
+          ROLE_ARN="${{ secrets.SPC_ROLE_ARN }}"
+          STS_ENDPOINT="https://sts.samsungspc.com"
 
-      - name: SPC OIDC Login
-        run: ./oidc.sh "${{ secrets.SPC_ROLE_ARN }}" "https://sts.samsungspc.com"
+          ID_TOKEN=$(curl -sSL -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
+            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.samsungspc.com" | jq -r '.value')
 
-      - name: Upload file to SPC S3
+          if [ -z "$ID_TOKEN" ] || [ "$ID_TOKEN" == "null" ]; then
+            echo "Error: OIDC token could not be fetched." >&2
+            exit 1
+          fi
+
+          echo "===== OIDC Token Claims ====="
+          echo "$ID_TOKEN" | cut -d "." -f2 | base64 -d | jq .
+          echo "============================="
+
+          RESPONSE=$(aws sts assume-role-with-web-identity \
+            --role-arn "${ROLE_ARN}" \
+            --role-session-name "GitHubActionsSession" \
+            --web-identity-token "${ID_TOKEN}" \
+            --endpoint-url "${STS_ENDPOINT}" \
+            --output json)
+
+          ACCESS_KEY=$(echo $RESPONSE | jq -r '.Credentials.AccessKeyId')
+          SECRET_KEY=$(echo $RESPONSE | jq -r '.Credentials.SecretAccessKey')
+          SESSION_TOKEN=$(echo $RESPONSE | jq -r '.Credentials.SessionToken')
+
+          echo "AWS_ACCESS_KEY_ID=$ACCESS_KEY" >> $GITHUB_ENV
+          echo "AWS_SECRET_ACCESS_KEY=$SECRET_KEY" >> $GITHUB_ENV
+          echo "AWS_SESSION_TOKEN=$SESSION_TOKEN" >> $GITHUB_ENV
+
+      - name: Copy files to SPC S3
         run: |
           export AWS_RESPONSE_CHECKSUM_VALIDATION=when_required
           export AWS_REQUEST_CHECKSUM_CALCULATION=when_required
-
+          
           aws s3 cp text.txt s3://dsung-dx-test-2/oidcTest/ \
-            --endpoint-url https://s3.us-east-1.samsungspc.com \
-            --region us-east-1
+            --endpoint-url https://s3.us-east-1.samsungspc.com --region us-east-1
